const INITIAL_STATE = {
  data: [
  {
  	"coreData": {
  		"id": "0a7ac8e20fa86700a10e4f8ce1050e43",
  		"number":"INC0211828",
  		"createdDate":"2018-09-17 03:18:05",
  		"lastUpdateDate":"2018-09-17 03:18:05",
  		"type":"INCIDENT",
  		"state":"New",
  		"shortDescription":"Agile Alert - Risk to complete releases",
  		"application":"Devops Analytics",
  		"assignee":""
  	},
  	"mlData":[],
  	"continuousML":false,
  	"automationData": {
  		"confidenceLevel":0.0,
  		"sourceServiceName":null,
  		"sourceJobName":null,
  		"automation":false,
  		"template":null,
  		"options":[],
  		"automationOptionData":null
  	},
  	"editingData": {
  		"editingUsers":null,
  		"editing":false
  	},
  	"serviceData": {
  		"parent":"",
  		"made_sla":"true",
  		"caused_by":"",
  		"watch_list":"",
  		"upon_reject":"Cancel all future Tasks",
  		"child_incidents":"0",
  		"hold_reason":"",
  		"approval_history":"",
  		"resolved_by":"",
  		"sys_updated_by":"admin",
  		"opened_by":"System Administrator",
  		"user_input":"",
  		"sys_created_on":"2018-09-17 03:18:05",
  		"sys_domain":"global",
  		"state":"New",
  		"sys_created_by":"admin",
  		"knowledge":"false",
  		"order":"",
  		"calendar_stc":"",
  		"closed_at":"",
  		"cmdb_ci":"",
  		"delivery_plan":"",
  		"impact":"3 - Medium",
  		"active":"true",
  		"work_notes_list":"",
  		"business_service":"",
  		"priority":"5 - Planning",
  		"sys_domain_path":"/",
  		"rfc":"",
  		"time_worked":"",
  		"expected_start":"",
  		"opened_at":"2018-09-17 03:18:05",
  		"business_duration":"",
  		"group_list":"",
  		"work_end":"",
  		"caller_id":"",
  		"resolved_at":"",
  		"approval_set":"",
  		"subcategory":"null",
  		"work_notes":"",
  		"close_code":"null",
  		"correlation_display":"",
  		"delivery_task":"",
  		"work_start":"",
  		"assignment_group":"",
  		"additional_assignee_list":"",
  		"business_stc":"",
  		"description":"",
  		"calendar_duration":"",
  		"close_notes":"",
  		"notify":"Do Not Notify",
  		"sys_class_name":"Incident",
  		"closed_by":"",
  		"follow_up":"",
  		"parent_incident":"",
  		"contact_type":"null",
  		"urgency":"3 - Medium",
  		"problem_id":"",
  		"company":"",
  		"reassignment_count":"0",
  		"activity_due":"UNKNOWN",
  		"severity":"3 - Low",
  		"comments":"",
  		"approval":"Not Yet Requested",
  		"sla_due":"UNKNOWN",
  		"comments_and_work_notes":"",
  		"due_date":"",
  		"sys_mod_count":"0",
  		"reopen_count":"0",
  		"sys_tags":"",
  		"escalation":"Normal",
  		"upon_approval":"Proceed to Next Task",
  		"location":"",
  		"category":"Inquiry / Help"
  	},
  	"slaData":[]
  }],
};

export default function (state = INITIAL_STATE, action) {
  switch (action.type) {
    default:
      return state;
  }
}
